const campo1 = document.querySelector("campo1")
const campo2 = document.querySelector("campo2")
const seletor = document.querySelector("seletor")
const botao = document.querySelector("botao")
let resposta = document.querySelector("resposta")